// <auto-generated />
using System;
using Gitgruppen.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitGruppen.Data.Migrations
{
    [DbContext(typeof(GitgruppenContext))]
    [Migration("20230113092843_DBContextUpdate")]
    partial class DBContextUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GitGruppen.Core.Member", b =>
                {
                    b.Property<string>("PersNr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersNr");

                    b.ToTable("Member");
                });

            modelBuilder.Entity("GitGruppen.Core.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SpotName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vehicleLicensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("vehicleLicensePlate");

                    b.ToTable("ParkingSpot");
                });

            modelBuilder.Entity("GitGruppen.Core.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("TimeArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeDeparture")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<string>("vehicleLicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("vehicleLicensePlate");

                    b.ToTable("Receipt");
                });

            modelBuilder.Entity("GitGruppen.Core.Vehicle", b =>
                {
                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Arrived")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("memberPersNr")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("vehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("LicensePlate");

                    b.HasIndex("memberPersNr");

                    b.HasIndex("vehicleTypeId");

                    b.ToTable("Vehicle");
                });

            modelBuilder.Entity("GitGruppen.Core.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NrOfSpaces")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleType");
                });

            modelBuilder.Entity("GitGruppen.Core.ParkingSpot", b =>
                {
                    b.HasOne("GitGruppen.Core.Vehicle", "vehicle")
                        .WithMany()
                        .HasForeignKey("vehicleLicensePlate");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("GitGruppen.Core.Receipt", b =>
                {
                    b.HasOne("GitGruppen.Core.Vehicle", "vehicle")
                        .WithMany()
                        .HasForeignKey("vehicleLicensePlate")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("GitGruppen.Core.Vehicle", b =>
                {
                    b.HasOne("GitGruppen.Core.Member", "member")
                        .WithMany()
                        .HasForeignKey("memberPersNr");

                    b.HasOne("GitGruppen.Core.VehicleType", "vehicleType")
                        .WithMany()
                        .HasForeignKey("vehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("member");

                    b.Navigation("vehicleType");
                });
#pragma warning restore 612, 618
        }
    }
}
